### ISSUE TITLE
LookUpOp

### ISSUE THREAD

**Issue by bolorundurowb** [bolorundurowb/dotNETANPR#1]
I am trying to see how i can use EmguCV (the .NET implementation of OpenCV) to replace these java classes since C# doesn't have a default class to handle these issues

**Comment by yemikudaisi** [comment]
Can you give a list of the classes and the packages, so I don't have to go through the whole source code. 

FYI: The javaanpr doesn't identify Nigerian plate numbers accurately.

**Comment by bolorundurowb** [comment]
Hello @yemikudaisi, thanks for reaching ut. I noticed that `javaanpr` doesn't identify Nigerian plates well and I'll look to make some modifications to the system to cater for that. As for the list, I would create a curated list and add it to this issue.
